import moment from 'moment';

import { SecondaryButton } from '@/components/ButtonStyles';
import { useUser } from '@/context/userContext';
import { Idiom } from '@/types';
import { highlightTokens } from '@/utils/highlightSearchTokens';
import {
  ExampleList,
  IdiomBody,
  IdiomHeader,
  IdiomSection,
  InfoElementKey,
  InfoSection,
  OriginSource,
  OriginText,
  PageBody,
  SectionBody,
  SectionHeader,
} from './DetailCard.styles';

type SearchMode = 'title' | 'keywords';

type DetailCardProps = {
  idiom: Idiom;
  openModal: () => void;
  searchTerm?: string;
  searchColumn: SearchMode;
};

const DetailCard = ({ idiom, openModal, searchTerm, searchColumn }: DetailCardProps) => {
  const { isAdmin } = useUser();
  const examples = Array.isArray(idiom.examples) ? idiom.examples : [];

  const safeSearchTerm = searchTerm ?? '';
  const safeSearchColumn: SearchMode = searchColumn ?? 'title';
  const hasSearch = safeSearchTerm.trim().length > 0;

  const shouldHighlight = (field: 'title' | 'definition' | 'origin' | 'examples') => {
    if (!hasSearch) return false;
    if (safeSearchColumn === 'title') return field === 'title';
    return true;
  };

  const displayTitle =
    idiom.title_general && idiom.title_general.trim() !== '' ? idiom.title_general : idiom.title;

  return (
    <PageBody>
      <IdiomHeader>
        <h1 data-testid='displaytitle'>
          {shouldHighlight('title') ? highlightTokens(displayTitle, safeSearchTerm) : displayTitle}
        </h1>
      </IdiomHeader>

      <IdiomBody>
        <InfoSection>
          <div>
            <InfoElementKey>Idiom</InfoElementKey>#{idiom.position}
          </div>
          <div data-testid='timestamp'>
            <InfoElementKey>Added:</InfoElementKey>
            {moment(idiom.timestamps).format('MM-DD-YY')}
          </div>
          {isAdmin && (
            <SecondaryButton className='btn btn-secondary' onClick={openModal}>
              Edit Idiom
            </SecondaryButton>
          )}
        </InfoSection>

        <div>
          <IdiomSection>
            {idiom.definition && (
              <SectionHeader>
                <h3>Definition</h3>
              </SectionHeader>
            )}
            <SectionBody>
              <div data-testid='definition'>
                {idiom.definition && shouldHighlight('definition')
                  ? highlightTokens(idiom.definition, safeSearchTerm)
                  : idiom.definition}
              </div>
            </SectionBody>
          </IdiomSection>

          <IdiomSection>
            {idiom.origin && idiom.origin.origin_text && (
              <SectionHeader>
                <h3>Origin</h3>
              </SectionHeader>
            )}
            <SectionBody>
              <OriginText>
                {idiom.origin?.origin_text && shouldHighlight('origin')
                  ? highlightTokens(idiom.origin.origin_text, safeSearchTerm)
                  : idiom.origin?.origin_text}
              </OriginText>
              {idiom.origin?.model && (
                <OriginSource>
                  - Generated by {idiom.origin?.model} on{' '}
                  {moment(idiom.origin?.updated_at).format('MM/DD/YY')}
                </OriginSource>
              )}
            </SectionBody>
          </IdiomSection>

          <IdiomSection>
            {idiom.examples && idiom.examples.length > 0 && (
              <SectionHeader>
                <h3>Examples</h3>
              </SectionHeader>
            )}
            <ExampleList data-testid='examples'>
              {examples.map((example) => {
                const text = example.example;
                return (
                  <li key={example.example_id}>
                    {shouldHighlight('examples') ? highlightTokens(text, safeSearchTerm) : text}
                  </li>
                );
              })}
            </ExampleList>
          </IdiomSection>
        </div>
      </IdiomBody>
    </PageBody>
  );
};

export default DetailCard;
