import moment from 'moment';

import { useUser } from '@/context/userContext';
import { Idiom } from '@/types';

import { SecondaryButton } from '@/components/ButtonStyles';
import {
  ExampleList,
  IdiomBody,
  IdiomHeader,
  IdiomSection,
  InfoElementKey,
  InfoSection,
  OriginSource,
  OriginText,
  PageBody,
  SectionBody,
  SectionHeader,
} from './DetailCard.styles';

type DetailCardProps = {
  idiom: Idiom;
  openModal: () => void;
};

const DetailCard = ({ idiom, openModal }: DetailCardProps) => {
  const { isAdmin } = useUser();
  const examples = Array.isArray(idiom.examples) ? idiom.examples : [];
  console.log(idiom.origin);
  return (
    <PageBody>
      <IdiomHeader>
        <h1 data-testid='displaytitle'>
          {idiom.title_general && idiom.title_general.trim() !== ''
            ? idiom.title_general
            : idiom.title}
        </h1>
      </IdiomHeader>

      <IdiomBody>
        <InfoSection>
          <div>
            <InfoElementKey>Idiom</InfoElementKey>#{idiom.position}
          </div>
          <div data-testid='timestamp'>
            <InfoElementKey>Added:</InfoElementKey>
            {moment(idiom.timestamps).format('MM-DD-YY')}
          </div>
          {isAdmin && (
            <SecondaryButton className='btn btn-secondary' onClick={openModal}>
              Edit Idiom
            </SecondaryButton>
          )}
        </InfoSection>

        <div>
          <IdiomSection>
            {idiom.definition && (
              <SectionHeader>
                <h3>Definition</h3>
              </SectionHeader>
            )}
            <SectionBody>
              <div data-testid='definition'>{idiom.definition}</div>
            </SectionBody>
          </IdiomSection>

          <IdiomSection>
            {idiom.origin && idiom.origin.origin_text && (
              <SectionHeader>
                <h3>Origin</h3>
              </SectionHeader>
            )}
            <SectionBody>
              <OriginText>{idiom.origin?.origin_text}</OriginText>
              {idiom.origin?.model && (
                <OriginSource>
                  - Generated by {idiom.origin?.model} on{' '}
                  {moment(idiom.origin?.updated_at).format('MM/DD/YY')}
                </OriginSource>
              )}
            </SectionBody>
          </IdiomSection>

          <IdiomSection>
            {idiom.examples && idiom.examples.length > 0 && (
              <SectionHeader>
                <h3>Examples</h3>
              </SectionHeader>
            )}
            <ExampleList data-testid='examples'>
              {examples.map((example) => (
                <li key={example.example_id}>{example.example}</li>
              ))}
            </ExampleList>
          </IdiomSection>
        </div>
      </IdiomBody>
    </PageBody>
  );
};

export default DetailCard;
