import moment from 'moment';

import { SecondaryButton } from '@/components/ButtonStyles';
import { useUser } from '@/context/userContext';
import { Idiom } from '@/types';

import {
  Card,
  CardBody,
  CardHeader,
  DefinitionText,
  ExampleItem,
  ExampleList,
  IdiomInfo,
  InfoElement,
  InfoElementKey,
  InfoSection,
  OriginSource,
  OriginText,
  SectionGroup,
  SectionHeader,
  UpdateExampleButtons,
} from './DetailCard.styles';

type DetailCardProps = {
  idiom: Idiom;
  openModal: () => void;
};

const DetailCard = ({ idiom, openModal }: DetailCardProps) => {
  const { isAdmin } = useUser();
  const examples = Array.isArray(idiom.examples) ? idiom.examples : [];
  console.log(idiom.origin);
  return (
    <Card className='card'>
      <CardHeader className='card-header'>
        <h1 data-testid='displaytitle'>
          {idiom.title_general && idiom.title_general.trim() !== ''
            ? idiom.title_general
            : idiom.title}
        </h1>
      </CardHeader>

      <CardBody className='card-body'>
        <InfoSection>
          <IdiomInfo>
            <InfoElement>
              <InfoElementKey>Idiom #:</InfoElementKey>
              {idiom.position}
            </InfoElement>
            <InfoElement data-testid='timestamp'>
              <InfoElementKey>Added on:</InfoElementKey>
              {moment(idiom.timestamps).format('MM-DD-YY')}
            </InfoElement>
            {idiom.contributor && (
              <InfoElement data-testid='contributor'>
                <InfoElementKey>Added by:</InfoElementKey>
                {idiom.contributor}
              </InfoElement>
            )}
          </IdiomInfo>
          {isAdmin && (
            <UpdateExampleButtons>
              <SecondaryButton className='btn btn-secondary' onClick={openModal}>
                Edit Idiom
              </SecondaryButton>
            </UpdateExampleButtons>
          )}
        </InfoSection>

        <SectionGroup>
          {idiom.definition && (
            <SectionHeader>
              <h3>Meaning</h3>
            </SectionHeader>
          )}
          <DefinitionText data-testid='definition'>{idiom.definition}</DefinitionText>

          {idiom.origin && idiom.origin.origin_text && (
            <SectionHeader>
              <h3>Origin</h3>
            </SectionHeader>
          )}
          <OriginText>{idiom.origin?.origin_text}</OriginText>
          {idiom.origin?.model && (
            <OriginSource>
              - Generated by {idiom.origin?.model} on{' '}
              {moment(idiom.origin?.updated_at).format('MM/DD/YY')}
            </OriginSource>
          )}

          {idiom.examples && idiom.examples.length > 0 && (
            <SectionHeader>
              <h3>Examples</h3>
            </SectionHeader>
          )}
          <ExampleList data-testid='examples'>
            {examples.map((example) => (
              <ExampleItem key={example.example_id}>{example.example}</ExampleItem>
            ))}
          </ExampleList>
        </SectionGroup>
      </CardBody>
    </Card>
  );
};

export default DetailCard;
