CREATE TABLE public.idioms (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(255),
  title_general varchar(255),
  definition text,
  contributor varchar(50),
  timestamps timestamptz
);

CREATE TABLE public.idiom_examples (
  example_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idiom_id integer NOT NULL REFERENCES public.idioms(id) ON DELETE CASCADE,
  example text
);

CREATE TABLE public.idiom_origins_ai (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idiom_id integer NOT NULL UNIQUE REFERENCES public.idioms(id) ON DELETE CASCADE,
  origin_text text NOT NULL,
  model text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  contributor text,
  submitted_at timestamptz DEFAULT now(),
  added boolean DEFAULT false
);

CREATE TABLE public.staging_scrapes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idiom_id integer REFERENCES public.idioms(id) ON DELETE CASCADE,
  job text NOT NULL,
  content text,
  status text,
  review_status text DEFAULT 'pending'
);

CREATE TABLE public.user_settings (
  user_id text PRIMARY KEY,
  theme text NOT NULL CHECK (theme IN ('light','dark','system'))
);
