version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev # Use the dev Dockerfile
    ports:
      - '3001:3001' # Map container port 3000 to host port 3000 (host:container)
    env_file:
      - ./server/.env # Load environment variables from server/.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app # Bind mount for hot-reloading
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev # Use the dev Dockerfile
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
    depends_on:
      - server
    volumes:
      - ./client:/app # Bind mount for hot-reloading
      - /app/node_modules
