# Use a Node.js image as the base
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Install tsx globally for running the TypeScript server with watch
RUN npm install -g tsx

# Copy the rest of the server code
COPY . .

EXPOSE 3001

CMD ["npm", "run", "start"]