name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Create server .env.test file from secrets
        run: |
          cat <<EOF > server/.env.test
          NODE_ENV=test
          PORT=3010
          CORS_ORIGIN=http://localhost:5174
          AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_ISSUER_BASE_URL=${{ secrets.AUTH0_ISSUER_BASE_URL }}
          DATABASE_URL_TEST=${{ secrets.DATABASE_URL_TEST }}
          EOF

      - name: Create client .env.test
        run: |
          echo "VITE_API_BASE_URL=http://localhost:3010" > client/.env.test

      - name: Create client e2e .env
        run: |
          cat <<EOF > client/e2e/.env
          TEST_ADMIN_EMAIL=${{ secrets.TEST_ADMIN_EMAIL }}
          TEST_ADMIN_PASSWORD=${{ secrets.TEST_ADMIN_PASSWORD }}
          TEST_USER_EMAIL=${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD=${{ secrets.TEST_USER_PASSWORD }}
          EOF

      - name: Install server dependencies
        run: npm ci
        working-directory: server

      - name: Install client dependencies
        run: npm ci
        working-directory: client

      - name: Install Playwright (browsers + CLI)
        run: npx playwright install --with-deps
        working-directory: client

      - name: Run E2E tests
        run: |
          chmod +x ../scripts/run-e2e.sh
          ../scripts/run-e2e.sh
        working-directory: client

      - name: Output debug info from Playwright (last-run.json)
        if: always()
        run: |
          echo "==== Playwright test-results ===="
          ls -R client/test-results || echo "No test-results directory found."
          cat client/test-results/.last-run.json || echo "No .last-run.json found."

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 7
